[client]
headless = true
logger.level = info

[logger]
level = info

[server]
headless = true
port = 8501
enableXsrfProtection = false
enableCORS = false
enableWebsocketCompression = true
maxMessageSize = 200
runOnSave = false

[browser]
serverAddress = localhost
gatherUsageStats = false

[theme]
primaryColor = "#2d5016"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"
